"""initial migration

Revision ID: 318867b8eecd
Revises: 
Create Date: 2026-04-08 00:10:17.678005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318867b8eecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='周期名称，如2026年Q1'),
    sa.Column('phase', sa.Integer(), nullable=True, comment='当前阶段 1-5'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否为当前活跃周期'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='是否已归档'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dept_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='部门名称'),
    sa.Column('group_name', sa.String(length=50), nullable=True, comment='组/中心名称'),
    sa.Column('profit_target', sa.Numeric(precision=14, scale=2), nullable=True, comment='人均利润目标值（万元）'),
    sa.Column('income_target', sa.Numeric(precision=14, scale=2), nullable=True, comment='人均自研收入目标值（万元）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='部门：实施交付部/产品研发部'),
    sa.Column('group_name', sa.String(length=50), nullable=True, comment='组/中心名称'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='岗位'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='岗级，如T1/S3/P5'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系方式（手机号），也是登录账号'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='密码哈希'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：管理员/项目经理/普通员工/领导'),
    sa.Column('assess_type', sa.String(length=20), nullable=False, comment='考核类型：基层管理人员/公共人员/业务人员/产品研发人员'),
    sa.Column('assess_type_secondary', sa.String(length=20), nullable=True, comment='第二考核类型（混合角色）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账号是否启用'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('rating', sa.String(length=20), nullable=True, comment='评定等级：优秀/合格/基本合格/不合格'),
    sa.Column('leader_comment', sa.String(length=1000), nullable=True, comment='领导评语'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator_coefficients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('grade', sa.String(length=20), nullable=False, comment='职级，如T1/S3/P5'),
    sa.Column('coefficient', sa.Numeric(precision=6, scale=4), nullable=True, comment='指标系数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_type_coefficients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('project_type', sa.String(length=50), nullable=False, comment='项目类型'),
    sa.Column('coefficient', sa.Numeric(precision=6, scale=4), nullable=True, comment='系数值'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('target_name', sa.String(length=50), nullable=False, comment='目标名称：产品合同目标值/科技创新目标值'),
    sa.Column('target_value', sa.Numeric(precision=14, scale=2), nullable=True, comment='目标值（万元）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='部门'),
    sa.Column('assess_type', sa.String(length=20), nullable=False, comment='考核类型'),
    sa.Column('description', sa.String(length=500), nullable=False, comment='加减分项说明'),
    sa.Column('value', sa.Numeric(precision=5, scale=2), nullable=True, comment='加减分值 -10~+10'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('evaluatee_id', sa.Integer(), nullable=False, comment='被评人ID'),
    sa.Column('evaluatee_name', sa.String(length=50), nullable=False, comment='被评人姓名'),
    sa.Column('evaluatee_assess_type', sa.String(length=20), nullable=False, comment='被评人考核类型'),
    sa.Column('evaluator_id', sa.Integer(), nullable=False, comment='评价人ID'),
    sa.Column('evaluator_name', sa.String(length=50), nullable=False, comment='评价人姓名'),
    sa.Column('evaluator_type', sa.String(length=20), nullable=False, comment='评价人类型：同事/上级领导/部门领导/基层管理互评/部门员工'),
    sa.Column('evaluator_order', sa.Integer(), nullable=True, comment='评价人序号（同事1~4）'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='是否已完成评分'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['evaluatee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='被评人ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='被评人姓名'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='部门'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='岗位'),
    sa.Column('assess_type', sa.String(length=20), nullable=False, comment='考核类型'),
    sa.Column('colleague1_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='同事1评分'),
    sa.Column('colleague2_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='同事2评分'),
    sa.Column('colleague3_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='同事3评分'),
    sa.Column('colleague4_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='同事4评分'),
    sa.Column('superior_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='上级领导评分'),
    sa.Column('dept_leader_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='部门领导评分'),
    sa.Column('weighted_total', sa.Numeric(precision=6, scale=2), nullable=True, comment='加权汇总得分'),
    sa.Column('final_score', sa.Numeric(precision=6, scale=2), nullable=True, comment='最终得分（折算到30分）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='部门'),
    sa.Column('group_name', sa.String(length=50), nullable=True, comment='组/中心'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='岗级'),
    sa.Column('assess_type', sa.String(length=20), nullable=False, comment='考核类型'),
    sa.Column('is_mixed_role', sa.Boolean(), nullable=True, comment='是否混合角色'),
    sa.Column('work_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='工作积分得分'),
    sa.Column('work_score_max', sa.Numeric(precision=5, scale=2), nullable=True, comment='工作积分满分（30或50）'),
    sa.Column('economic_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='经济指标得分'),
    sa.Column('economic_score_max', sa.Numeric(precision=5, scale=2), nullable=True, comment='经济指标满分（20或30）'),
    sa.Column('key_task_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='重点任务得分（/10，仅基层管理人员）'),
    sa.Column('work_goal_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='工作目标完成度得分（/70，仅公共人员）'),
    sa.Column('eval_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='综合评价得分（/30）'),
    sa.Column('bonus_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='加减分（±10）'),
    sa.Column('total_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='总分'),
    sa.Column('ranking', sa.Integer(), nullable=True, comment='排名（同部门同类型内）'),
    sa.Column('rating', sa.String(length=20), nullable=True, comment='评定等级'),
    sa.Column('leader_comment', sa.String(length=1000), nullable=True, comment='领导评语'),
    sa.Column('secondary_assess_type', sa.String(length=20), nullable=True, comment='第二考核类型'),
    sa.Column('secondary_work_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='第二身份工作积分得分'),
    sa.Column('secondary_economic_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='第二身份经济指标得分'),
    sa.Column('secondary_key_task_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='第二身份重点任务得分'),
    sa.Column('secondary_eval_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='第二身份综合评价得分'),
    sa.Column('secondary_bonus_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='第二身份加减分'),
    sa.Column('secondary_total_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='第二身份总分'),
    sa.Column('no_excellent_flag', sa.Boolean(), nullable=True, comment='不可评优标记（同年2次基本合格）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_task_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='重点任务分数 0~10'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('project_code', sa.String(length=50), nullable=False, comment='项目令号'),
    sa.Column('project_name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('project_status', sa.String(length=20), nullable=True, comment='项目状态'),
    sa.Column('project_type', sa.String(length=20), nullable=False, comment='项目类型：集成/综合/自研/运营'),
    sa.Column('impl_method', sa.String(length=20), nullable=True, comment='实施方式：服务/产品+服务'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='主承部门'),
    sa.Column('contract_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='合同金额（万元）'),
    sa.Column('project_profit', sa.Numeric(precision=14, scale=2), nullable=True, comment='项目利润（万元）'),
    sa.Column('self_dev_income', sa.Numeric(precision=14, scale=2), nullable=True, comment='自研收入（万元）'),
    sa.Column('product_contract_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='产品合同金额（万元）'),
    sa.Column('presale_progress', sa.Numeric(precision=6, scale=4), nullable=True, comment='售前活动进度系数'),
    sa.Column('delivery_progress', sa.Numeric(precision=6, scale=4), nullable=True, comment='交付活动进度系数'),
    sa.Column('pm_id', sa.Integer(), nullable=True, comment='项目经理ID'),
    sa.Column('pm_name', sa.String(length=50), nullable=True, comment='项目经理姓名'),
    sa.Column('economic_scale_coeff', sa.Numeric(precision=10, scale=4), nullable=True, comment='经济规模系数（自动计算）'),
    sa.Column('project_type_coeff', sa.Numeric(precision=6, scale=4), nullable=True, comment='项目类型系数（自动计算）'),
    sa.Column('workload_coeff', sa.Numeric(precision=10, scale=4), nullable=True, comment='工作量系数=经济规模系数×项目类型系数'),
    sa.Column('signing_probability', sa.Numeric(precision=5, scale=4), nullable=True, comment='签约概率，未签约项目使用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='申报员工ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='申报员工姓名'),
    sa.Column('activity_name', sa.String(length=200), nullable=False, comment='活动名称'),
    sa.Column('activity_type', sa.String(length=20), nullable=False, comment='活动类型：公共活动/转型活动'),
    sa.Column('man_months', sa.Numeric(precision=8, scale=2), nullable=True, comment='投入人力（人月）'),
    sa.Column('complexity', sa.String(length=20), nullable=False, comment='复杂度：较简单/中等/极大'),
    sa.Column('scale_value', sa.Numeric(precision=6, scale=4), nullable=True, comment='活动规模值（自动计算）'),
    sa.Column('complexity_value', sa.Numeric(precision=6, scale=4), nullable=True, comment='活动复杂性值（自动计算）'),
    sa.Column('workload_coeff', sa.Numeric(precision=8, scale=4), nullable=True, comment='工作量系数=规模值×复杂性值'),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True, comment='积分=基础分值10×工作量系数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：已申报/管理员已修改'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='部门'),
    sa.Column('assess_type', sa.String(length=20), nullable=False, comment='考核类型'),
    sa.Column('project_score_total', sa.Numeric(precision=10, scale=2), nullable=True, comment='项目积分合计'),
    sa.Column('public_score_total', sa.Numeric(precision=10, scale=2), nullable=True, comment='公共积分合计'),
    sa.Column('transform_score_total', sa.Numeric(precision=10, scale=2), nullable=True, comment='转型积分合计'),
    sa.Column('total_score', sa.Numeric(precision=10, scale=2), nullable=True, comment='总积分'),
    sa.Column('normalized_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='开方归一化得分'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_goal_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='被评公共人员ID'),
    sa.Column('leader_id', sa.Integer(), nullable=False, comment='评分领导ID'),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True, comment='工作目标完成度得分（满分70）'),
    sa.Column('comment', sa.String(length=1000), nullable=True, comment='文字评语'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('relation_id', sa.Integer(), nullable=False, comment='互评关系ID'),
    sa.Column('evaluatee_id', sa.Integer(), nullable=False, comment='被评人ID'),
    sa.Column('evaluator_id', sa.Integer(), nullable=False, comment='评价人ID'),
    sa.Column('dimension', sa.String(length=50), nullable=False, comment='评分维度'),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False, comment='该维度满分'),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True, comment='评分'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['evaluatee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['eval_relations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='员工所属部门'),
    sa.Column('participation_coeff', sa.Numeric(precision=5, scale=4), nullable=True, comment='参与度系数 0~1'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：未填/已提交/已修改'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False, comment='所属考核周期'),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('employee_name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='项目ID（公共积分为null）'),
    sa.Column('project_name', sa.String(length=200), nullable=True, comment='项目名称'),
    sa.Column('phase', sa.String(length=20), nullable=False, comment='项目阶段：售前/交付/公共/转型'),
    sa.Column('base_score', sa.Numeric(precision=8, scale=2), nullable=True, comment='基础分值：售前50/交付100/公共10/转型10'),
    sa.Column('progress_coeff', sa.Numeric(precision=6, scale=4), nullable=True, comment='进度系数'),
    sa.Column('workload_coeff', sa.Numeric(precision=10, scale=4), nullable=True, comment='工作量系数'),
    sa.Column('participation_coeff', sa.Numeric(precision=5, scale=4), nullable=True, comment='参与系数'),
    sa.Column('participant_name', sa.String(length=50), nullable=True, comment='参与人'),
    sa.Column('participant_role', sa.String(length=20), nullable=True, comment='参与人角色'),
    sa.Column('work_description', sa.String(length=500), nullable=True, comment='完成的工作'),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True, comment='分数合计=基础分值×进度系数×工作量系数×参与系数'),
    sa.Column('modified_by', sa.String(length=50), nullable=True, comment='修改人'),
    sa.Column('modified_at', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_details')
    op.drop_table('participations')
    op.drop_table('eval_scores')
    op.drop_table('work_goal_scores')
    op.drop_table('score_summaries')
    op.drop_table('public_scores')
    op.drop_table('projects')
    op.drop_table('key_task_scores')
    op.drop_table('final_results')
    op.drop_table('eval_summaries')
    op.drop_table('eval_relations')
    op.drop_table('bonus_records')
    op.drop_table('special_targets')
    op.drop_table('project_type_coefficients')
    op.drop_table('indicator_coefficients')
    op.drop_table('employees')
    op.drop_table('dept_targets')
    op.drop_table('cycles')
    # ### end Alembic commands ###
