"""add_project_fields

Revision ID: fadc6745b411
Revises: 318867b8eecd
Create Date: 2026-04-08 20:44:29.398947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadc6745b411'
down_revision: Union[str, Sequence[str], None] = '318867b8eecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('customer_name', sa.String(length=200), nullable=True, comment='客户名称'))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=True, comment='项目开始时间'))
    op.add_column('projects', sa.Column('end_date', sa.DateTime(), nullable=True, comment='项目结束时间'))
    op.add_column('projects', sa.Column('used_presale_progress', sa.Numeric(precision=6, scale=4), nullable=True, comment='已使用进度系数-售前活动'))
    op.add_column('projects', sa.Column('used_delivery_progress', sa.Numeric(precision=6, scale=4), nullable=True, comment='已使用进度系数-交付活动'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'used_delivery_progress')
    op.drop_column('projects', 'used_presale_progress')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'customer_name')
    # ### end Alembic commands ###
